<?php

namespace App\Providers;

use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;

class MD5ServiceProvider extends EloquentUserProvider
{

    //继承EloquentUserProvider类，调用父类的构造函数
    public function __construct($hasher, $model)
    {
        parent::__construct($hasher, $model);
    }

    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * 覆盖父类方法 不操作更新remember_token
     *
     * @param UserContract $user
     * @param string $token
     */
    public function updateRememberToken(UserContract $user, $token)
    {
        //parent::updateRememberToken($user, $token); // TODO: Change the autogenerated stub
    }

    public function validateCredentials(UserContract $user, array $credentials)
    {
        $plain = $credentials['admin_password'];

        return $this->hasher->check($plain, $user->getAuthPassword());
    }
}